version: 1.0.{build}
image:
- Visual Studio 2015
test: off
build:
  parallel: true
platform:
  - x64
environment:
  matrix:
  - CONFIG: Debug
  - CONFIG: Release
init:
  - "set PYTHONHOME=C:\\Miniconda36-x64"
  - "set PATH=%PYTHONHOME%;%PYTHONHOME%\\Scripts;%PYTHONHOME%\\Library\\bin;%PATH%"
  - set CMAKE_GENERATOR="Visual Studio 14 2015"
install:
  - conda config --system --set always_yes yes --set changeps1 no
  - conda config --system --append channels conda-forge
  - conda install -y -n base conda-devenv
  - conda devenv
  - call activate reaktoro
  - set CMAKE_ARCH=x64
  - set CMAKE_INCLUDE_PATH=%CONDA_PREFIX%\Library\include
  - conda list
build_script:
  - mkdir build
  - mkdir artifacts
  - cd build
  - set MSBuildLogger="C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - cmake -G %CMAKE_GENERATOR% -A "%CMAKE_ARCH%" -DBUILD_ALL=ON -DCMAKE_BUILD_TYPE=%CONFIG% -DCMAKE_INCLUDE_PATH="%CMAKE_INCLUDE_PATH%" -DBOOST_INCLUDE_DIR="%CMAKE_INCLUDE_PATH%" -DCMAKE_INSTALL_PREFIX=../artifacts -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON "-DTHIRDPARTY_COMMON_ARGS=-DCMAKE_VERBOSE_MAKEFILE:BOOL=ON" ..
  - cmake --build . --config %CONFIG% --target install -- /m /v:m /logger:%MSBuildLogger%
  - dir
  - dir /S ..\artifacts
