{{ min_conda_devenv_version("1.1") }}

name: reaktoro

{% set python_version = os.environ.get("PY_VER", "3.7") %}
{% set debug = os.environ.get("CONFIG", "").lower() == "debug" %}

dependencies:
  - boost=1.70
  - cmake=3.14
  - invoke
  - ninja>=1.9.0
  - numpy
  - pandas
  - pip
  - pip:
    - sphinx
    - sphinx-autobuild
    - sphinx_rtd_theme
    - sphinxcontrib-images
  {% if not debug %}
  # Cannot link the Release version of `pugixml` (from conda) to the Debug version of Reaktoro
  - pugixml
  {% endif %}
  - pybind11=2.3.0
  - pytest
  - pytest-cpp
  - pytest-datadir
  - pytest-lazy-fixture
  - pytest-regressions
  - pytest-timeout
  - pytest-xdist
  - python={{ python_version }}
  - tabulate
  - gxx_linux-64=7.3.0             # [linux]
  - libstdcxx-ng                   # [linux]
  - ccache                         # [unix]
  - clcache                        # [win]

environment:

  PYTHONPATH:
    - {{ root }}/artifacts/python/lib/python{{ python_version }}/site-packages   # [unix]
    - {{ root }}/build/lib/python{{ python_version }}/site-packages              # [unix]
    - {{ root }}/build/lib64/python{{ python_version }}/site-packages            # [unix]
    - {{ root }}\artifacts\python\Lib\site-packages                              # [win]
    - {{ root }}\build\lib\python{{ python_version }}\site-packages              # [win]

  LD_LIBRARY_PATH:                                                   # [unix]
    - {{ root }}/artifacts/lib                                       # [unix]

  PATH:                                                              # [win]
    - {{ root }}\artifacts\bin                                       # [win]

  CC: clcache                               # [win]
  CXX: clcache                              # [win]
  CLCACHE_BASEDIR: {{ root }}               # [win]
  # Improves CLCACHE robustness, minimizing the chance of a race condition
  CLCACHE_OBJECT_CACHE_TIMEOUT_MS: 3600000  # [win]
