name: reaktoro

{% set python_version = "3.6" %}

dependencies:
  - boost=1.67
  - cmake>=3.9
  - invoke
  - ninja
  - numpy
  - pandas
  - pugixml
  - pybind11
  - pytest
  - pytest-cpp
  - pytest-datadir
  - pytest-lazy-fixture
  - pytest-regressions
  - pytest-timeout
  - pytest-xdist
  - python={{ python_version }}
  - tabulate
{% if sys.platform.startswith('linux') %}
  - gxx_linux-64=7.3.0
  - libstdcxx-ng
{% endif %}
{% if sys.platform.startswith('linux') and sys.platform.startswith('osx') %}
  - ccache
{% endif %}

environment:
  {% if os.sys.platform != 'win32' %}

  PYTHONPATH:
    - {{ root }}/artifacts/python/lib/python{{ python_version }}/site-packages

  # Shared library must be in LD_LIBRARY_PATH in order for `reaktoro` to be successfully imported
  LD_LIBRARY_PATH:
    - {{ root }}/artifacts/lib

  {% else %}

  PYTHONPATH:
    - {{ root }}\artifacts\python\Lib\site-packages

  PATH:
    - {{ root }}\artifacts\bin

  {% endif %}
