name: reaktoro

dependencies:
  - boost=1.67
  - cmake
{% if sys.platform.startswith('linux') %}
  - gxx_linux-64=7.3.0
  - libstdcxx-ng
{% endif %}
  - ninja
  - numpy
  - pybind11
  - pyinstaller
  - pytest-cpp
  - pytest-datadir
  - pytest-lazy-fixture
  - pytest-regressions
  - pytest-timeout
  - pytest-xdist
  - pytest
  - python=3.6
  - tabulate
