name: reaktoro

{% set python_version = os.environ.get("PY_VER", "3.7") %}
{% set debug = os.environ.get("CONFIG", "").lower() == "debug" %}
{% set use_openlibm = os.environ.get("REAKTORO_USE_OPENLIBM", "0").strip() != "0" %}

channels:
  - conda-forge

dependencies:
  # C++ compilers
  - gxx_linux-64=7.3.0  # [linux]
  - clangxx=9.0.0  # [osx]

  # C++ libraries
  - pybind11>=2.5.0
  - thermofun==0.3.7
  - nlohmann_json==3.6.1
  # - yaml-cpp  # current version on conda-forge, v0.63, has no support for enconding nan and inf values (using master version with git submodule)
  {% if not debug %}
  - pugixml  # cannot link the Release version of `pugixml` (from conda) to the Debug version of Reaktoro
  {% endif %}
  {% if use_openlibm %}
  - openlibm
  {% endif %}

  # Documentation dependencies
  - doxygen=1.8.20                 # [linux]
  - graphviz                       # [linux]
  - sphinx==1.8.5
  - sphinx-autobuild
  - sphinx_rtd_theme
  - pip:
    - sphinxcontrib-images
    - oyaml

  # Python dependencies
  - python={{ python_version }}
  - numpy
  - pandas
  - pip
  - fire
  - tabulate

  # Python test dependencies
  - pytest
  - pytest-cpp
  - pytest-datadir
  - pytest-lazy-fixture
  - pytest-regressions
  - pytest-timeout
  - pytest-xdist

  # Utilities dependencies
  - cmake>=3.17
  - git>=2.28
  - ninja>=1.9.0
  - ccache                         # [unix]
  - clcache                        # [win]
  - catch2
  - invoke

environment:

  PYTHONPATH:
    - {{ root }}/artifacts/python/lib/python{{ python_version }}/site-packages   # [unix]
    - {{ root }}/build/lib/python{{ python_version }}/site-packages              # [unix]
    - {{ root }}/build/lib64/python{{ python_version }}/site-packages            # [unix]
    - {{ root }}\artifacts\python\Lib\site-packages                              # [win]
    - {{ root }}\build\lib\python{{ python_version }}\site-packages              # [win]

  LD_LIBRARY_PATH:                                                   # [unix]
    - {{ root }}/artifacts/lib                                       # [unix]

  PATH:                                                              # [win]
    - {{ root }}\artifacts\bin                                       # [win]

  CC: clcache                               # [win]
  CXX: clcache                              # [win]
  CLCACHE_BASEDIR: {{ root }}               # [win]
  # Improves CLCACHE robustness, minimizing the chance of a race condition
  CLCACHE_OBJECT_CACHE_TIMEOUT_MS: 3600000  # [win]
